name: deploy paytr

on:
  pull_request:
    branches:
      - main

jobs:
  build: 
    name: Compile ts files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - run: npm ci
    - run: npm run build

  deploy:
    name: deploy to heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy paytr
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: "herityjohnny14@gmail.com"
